// ============================================
// EXPORTLOTS.COM — VEHICLES DATABASE
// VA fills this daily from Manheim
// Format: one object per vehicle
// ============================================

const VEHICLES = [
  {
    id: "4T1B11HK3KU800400",
    vin: "4T1B11HK3KU800400",
    year: 2019,
    make: "Toyota",
    model: "Camry LE",
    mileage: 278231,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "Celestial Silver",
    grade: 2.4,
    mmr: 4550,
    titleStatus: "absent",      // clean / salvage / absent / rebuilt
    originPort: "TX",           // NJ / GA / TX / CA / FL
    auctionType: "buynow",      // buynow / auction
    auctionDate: null,          // null for buynow, "2026-05-25T14:00" for auction
    stockPhoto: "https://i.ibb.co/mxyjpPd/Celestial-Silver-2019-Camry-LE.jpg",
    damage: [
      { zone: "windshield",       status: "damage",  desc: "Cracked" },
      { zone: "frontBumper",      status: "damage",  desc: "Broken" },
      { zone: "hood",             status: "damage",  desc: "Dents" },
      { zone: "leftFrontDoor",    status: "damage",  desc: "Dents" },
      { zone: "leftFender",       status: "damage",  desc: "Dents" },
      { zone: "leftFender",       status: "repair",  desc: "Previous repair" },
      { zone: "leftRearDoor",     status: "damage",  desc: "Dents x2" },
      { zone: "rightRearDoor",    status: "repair",  desc: "Previous repair" },
      { zone: "rightFrontDoor",   status: "damage",  desc: "Dents" },
      { zone: "rearBumper",       status: "damage",  desc: "Dents" },
    ],
    interiorWarnings: [
      "Engine warning light on",
      "Traction control warning on",
      "All seats worn/stained",
      "Headliner hole"
    ],
    owners: 3,
    accidents: 1,
    active: true,
  },

  // 2025 Toyota Camry SE Hybrid — Buy Now
  {
    id: "4T1DAACK7SU584096",
    vin: "4T1DAACK7SU584096",
    year: 2025,
    make: "Toyota",
    model: "Camry SE Hybrid",
    mileage: 12500,
    engine: "2.5L 4-Cyl Hybrid",
    transmission: "CVT",
    drive: "FWD",
    color: "Ice Cap White",
    grade: null,
    mmr: 27400,
    buyNow: 19000,
    titleStatus: "clean",
    originPort: "NJ",
    auctionType: "buynow",
    auctionDate: null,
    expiryDate: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/5xW514Rt/ce-Cap-White-2025-Camry-SE-Hybrid.jpg",
    damage: [],
    interiorWarnings: ["No condition report available"],
    owners: 2,
    accidents: 2,
    active: true,
  },

  // 2022 Toyota Camry LE — Timed Auction ending in ~2.5 hours
  {
    id: "4T1C11AK1NU637040",
    vin: "4T1C11AK1NU637040",
    year: 2022,
    make: "Toyota",
    model: "Camry LE",
    mileage: 237637,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "White",
    grade: 2.9,
    mmr: 6200,
    buyNow: 7500,
    titleStatus: "unknown",
    originPort: "NJ",
    auctionType: "auction",
    auctionDate: new Date(Date.now() + 2.5 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/KHV6q6y/White-2022-Camry-LE.png",
    damage: [
      { zone: "frontBumper",  status: "damage", desc: "Broken" },
      { zone: "hood",         status: "damage", desc: "Grille broken" },
      { zone: "roof",         status: "damage", desc: "Dents" },
      { zone: "leftFender",   status: "damage", desc: "Liner missing" },
      { zone: "leftRearDoor", status: "damage", desc: "Dents" },
      { zone: "rearBumper",   status: "damage", desc: "Scratches" },
      { zone: "rightFender",  status: "damage", desc: "Dents" },
    ],
    interiorWarnings: ["All seats worn/stained", "Console worn"],
    owners: 1,
    accidents: 0,
    active: true,
  },

  // 2019 Toyota Camry SE — Red Light AS-IS, transmission codes
  {
    id: "4T1B11HK9KU682627",
    vin: "4T1B11HK9KU682627",
    year: 2019,
    make: "Toyota",
    model: "Camry SE",
    mileage: 381495,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "Super White",
    grade: 4.1,
    mmr: 3900,
    buyNow: null,
    startingBid: 8400,
    titleStatus: "unknown",
    originPort: "NJ",
    auctionType: "auction",
    auctionDate: new Date(Date.now() + 22.5 * 3600 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 22.5 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/rR3MZ1Cg/Super-White-2019-Camry-SE.png",
    damage: [
      { zone: "frontBumper",   status: "damage", desc: "Misaligned, molding damage, paint damage" },
      { zone: "leftFrontDoor", status: "damage", desc: "Paint chipped, small dent" },
      { zone: "leftRearDoor",  status: "damage", desc: "Small dent" },
      { zone: "rearBumper",    status: "damage", desc: "Severe damage" },
    ],
    interiorWarnings: [
      "Interior panels worn/scratched",
      "Steering wheel light scratches",
      "3 wheels cosmetic damage",
      "⚠️ Active DTC codes: P2757 P2714 P0796 P2808 — transmission solenoid faults",
      "Red Light / AS-IS — no arbitration",
    ],
    owners: 2,
    accidents: 2,
    active: true,
  },

  // 2020 Toyota Camry SE — Black, Grade 4.0, 1 owner, 0 accidents
  {
    id: "4T1G11AKXLU397131",
    vin: "4T1G11AKXLU397131",
    year: 2020,
    make: "Toyota",
    model: "Camry SE",
    mileage: 263769,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "Midnight Black",
    grade: 4.0,
    mmr: 5400,
    buyNow: 7499,
    startingBid: null,
    titleStatus: "unknown",
    originPort: "TX",
    auctionType: "buynow",
    auctionDate: null,
    expiryDate: new Date(Date.now() + 22.5 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/DjmtVgY/Midnight-Black-2020-Camry-SE.png",
    damage: [
      { zone: "frontBumper",    status: "damage", desc: "Paint damage" },
      { zone: "hood",           status: "damage", desc: "Paint damage" },
      { zone: "leftFender",     status: "repair", desc: "Substandard paint repair" },
      { zone: "leftFrontDoor",  status: "damage", desc: "Light scratch" },
      { zone: "leftRearDoor",   status: "damage", desc: "Light scratch" },
      { zone: "leftFender",     status: "damage", desc: "Paint damage" },
      { zone: "rearBumper",     status: "damage", desc: "Light scratch" },
      { zone: "rightFender",    status: "damage", desc: "Light scratch" },
      { zone: "rightRearDoor",  status: "damage", desc: "Light scratch" },
    ],
    interiorWarnings: [
      "2 wheels cosmetic damage",
    ],
    owners: 1,
    accidents: 0,
    active: true,
  },

  // 2019 Toyota Camry SE — Gray, Red Light, Title Absent, FL
  {
    id: "4T1B11HK2KU232026",
    vin: "4T1B11HK2KU232026",
    year: 2019,
    make: "Toyota",
    model: "Camry SE",
    mileage: 240420,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "Predawn Gray",
    grade: null,
    mmr: 3950,
    buyNow: 6500,
    startingBid: null,
    titleStatus: "absent",
    originPort: "NJ",
    auctionType: "buynow",
    auctionDate: null,
    expiryDate: new Date(Date.now() + 9.9 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/DjmtVgY/Midnight-Black-2020-Camry-SE.png",
    damage: [],
    interiorWarnings: [
      "Red Light / AS-IS — no arbitration",
      "No condition report available",
    ],
    owners: 3,
    accidents: 0,
    active: true,
  },

  // 2018 Toyota Camry XLE — Black, Red Light, Transmission Problem, GA
  {
    id: "4T1B11HK0JU141268",
    vin: "4T1B11HK0JU141268",
    year: 2018,
    make: "Toyota",
    model: "Camry XLE",
    mileage: 240283,
    engine: "2.5L 4-Cyl",
    transmission: "Auto",
    drive: "FWD",
    color: "Midnight Black",
    grade: 3.7,
    mmr: 5000,
    buyNow: 7950,
    startingBid: null,
    titleStatus: "unknown",
    originPort: "NJ",
    auctionType: "buynow",
    auctionDate: null,
    expiryDate: new Date(Date.now() + 22.4 * 3600 * 1000).toISOString(),
    stockPhoto: "https://i.ibb.co/KpFHTwdX/2018-Camry-XLE-black.jpg",
    damage: [],
    interiorWarnings: [
      "⚠️ TRANSMISSION PROBLEM — announced by seller",
      "Red Light / AS-IS — no arbitration",
      "No condition report available",
    ],
    owners: 2,
    accidents: 2,
    active: true,
  },

  // ---- ADD MORE VEHICLES BELOW ----
  // VA template:
  // {
  //   id: "VIN",
  //   vin: "VIN",
  //   year: YYYY,
  //   make: "Make",
  //   model: "Model Trim",
  //   mileage: 00000,
  //   engine: "X.XL X-Cyl",
  //   transmission: "Auto",
  //   drive: "FWD/RWD/AWD/4WD",
  //   color: "Color Name",
  //   grade: X.X,
  //   mmr: XXXXX,
  //   titleStatus: "clean/salvage/absent/rebuilt",
  //   originPort: "NJ/GA/TX/CA/FL",
  //   auctionType: "buynow/auction",
  //   auctionDate: null or "YYYY-MM-DDTHH:MM",
  //   stockPhoto: "URL to stock photo",
  //   damage: [ { zone: "...", status: "damage/repair/clean/unknown", desc: "..." } ],
  //   interiorWarnings: [],
  //   owners: X,
  //   accidents: X,
  //   active: true,
  // },
];

if (typeof module !== 'undefined') module.exports = { VEHICLES };
